title: Welcome to Valhalla  
author: Ahmad Bitar
email: ahmad.bitar@hotmail.com
description: Hello World and welcome to my site, here i will be discussing about my 
journey on how and when i started my love towards coding. Hope you all have a blessed day.

# social links
twitter_username: ahmadbitar222
github_username:  ahmadbitar22

theme: minima 
